# versionは3系が最新版で、versionによって書き方が異なる
version: '3'
services:
  mysql:
    # Dockerfileからビルドすることを示す
    build: ./mysql/db/ 
    volumes:
      # 初期データをマウントする場所
      - ./mysql/DB:/docker-entrypoint-initdb.d 
    # イメージの名前
    image: original_mysql_world
    # コンテナ内のMySQLを起動する際のパスワードを設定
    environment:
      - MYSQL_ROOT_PASSWORD=1234